os: osx
osx_image: xcode9.3
script:
  - xcodebuild -version
  - carthage version
  - carthage bootstrap --platform iOS
  - set -o pipefail && env "NSUnbufferedIO=YES" xcodebuild test -scheme Chuck -project Chuck.xcodeproj | xcpretty -f `xcpretty-travis-formatter`